package first.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 17 18:10:20 IST 2019]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class TurbineGroup
    extends first.om.BaseTurbineGroup
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1547728820457L;

}
